import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import StyledComponentsRegistry from "./components/styledComponentsRegistry";
import LocalizationContextProvider from "./context/LocalizationPovider";
import { ThemeModeProvider } from "./context/ThemeModeProvider";
import NotiStackProvider from "./components/NotiStack";
import DeleteModalContext from "./context/DeleteModalContext";
import DeleteModal from "./components/DeleteModal/DeleteModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <StyledComponentsRegistry>
            <ThemeModeProvider>
              <AuthProvider>
                <LocalizationContextProvider>
                  <DeleteModalContext>
                    <DeleteModal />
                    <NotiStackProvider>
                      {children}
                    </NotiStackProvider>
                  </DeleteModalContext>
                </LocalizationContextProvider>
              </AuthProvider>
            </ThemeModeProvider>
          </StyledComponentsRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
